blank_issues_enabled: false
contact_links:
  - name: Wechat
    url: https://www.obsidians.io/wechat
    about: Follow the Obsidian Labs official wechat account.
  - name: Telegram
    url: https://t.me/blackide
    about: Ask (and answer) questions at the Obsidian Labs Telegram group
